// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VxeButton: typeof import('vxe-table')['Button']
    VxeColumn: typeof import('vxe-table')['Column']
    VxeGrid: typeof import('vxe-table')['Grid']
    VxeInput: typeof import('vxe-table')['Input']
    VxeOption: typeof import('vxe-table')['Option']
    VxeSelect: typeof import('vxe-table')['Select']
    VxeTable: typeof import('vxe-table')['Table']
    VxeToolbar: typeof import('vxe-table')['Toolbar']
  }
}
