// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartPreviewImg: typeof import('./chartPreviewImg.vue')['default']
    EchartsCode: typeof import('./echarts-code.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    LeftEditor: typeof import('./leftEditor.vue')['default']
    RightChart: typeof import('./rightChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
